
services:
  app:
    container_name: 'preparacao-app'
    build: .
    image: evsilva/fiap-techchalg-preparacao:dev
    ports:
      - '0.0.0.0:8080:8080'
  redis:
    container_name: 'preparacao-db'
    image: redis:alpine3.19
  message-broker:
    container_name: 'preparacao-message-broker'
    image: rabbitmq:3.12.14-management-alpine
    ports:
      - "25672:25672"
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER=fiap
      - RABBITMQ_DEFAULT_PASS=Rabbit!1@2#3